name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Setup JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: temurin
      - name: Cache Gradle packages
        uses: actions/cache@v4.0.2
        with:
          key: "$GITHUB_SHA"
          path: |
            ~/builds
            ~/build
            ~/.gradle
      - name: Build with Gradle
        run: ./gradlew assemble test check
  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Login ghcr
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: docker login ghcr.io --username warriorzz --password "$GITHUB_TOKEN"
      - name: Build and Push Image
        run: |
          docker buildx build \
                  --tag ghcr.io/warriorzz/airlanding/airlanding:latest \
                  --tag ghcr.io/warriorzz/airlanding/airlanding:"$GITHUB_SHA" \
                  --platform linux/amd64,linux/arm64/v8 \
                  --file ./Dockerfile \
                  --output type=image,push=true .
